<div class="h4">Specific Scanners/Misc Tools</div>
<div>(not always needed, but I for instance have updated copies of all of these &quot;just in case&quot;). These can be used to help clean, badly infected computers:</div>
<ul class="list-group">
  <li class="list-group-item"><a href="http://www.bleepingcomputer.com/combofix/how-to-use-combofix" target="_blank"><img class="icon--size32 mr-2" src="/techHQ/progIcons/security/combofix.png" alt="Combofix Graphic">ComboFix</a>
    <div>I have seen ComboFix, first-hand help computers that were badly infected; new users, should only use this if reformatting SEEMS like the only hope, after MalwareBytes &quot;failed&apos;. Note: At that time I had no idea about RKill (listed below) so instead of running Combofix, running RKill THEN Malwarebytes, may have worked as well</div>
  </li>
  <li class="list-group-item"><a href="https://www.bleepingcomputer.com/download/rkill/" target="_blank"><img class="icon--size32 mr-2" src="/techHQ/progIcons/security/malware/rkill.png" alt="Rkill graphic">RKill</a>2020 note: I am not sure how useful this is in Windows 10, or if this is even updated anymore<br/>- Listed on many BleepingComputers tutorials as what to use before Malwarebytes on pesky infections that contain rootkits that try to disable Malwarebytes from cleaning your computer</li>
  <li class="list-group-item"><a href="https://usa.kaspersky.com/downloads/tdsskiller" target="_blank"><img class="icon--size32 mr-2" src="/techHQ/progIcons/security/malware/TDSSKiller.png" alt="TDSSKiller graphic">TDSSKiller</a> Kaspersky's offering to remove TDSS infections</li>
  <li class="list-group-item"><a href="https://www.malwarebytes.com/adwcleaner/" target="_blank"><img class="icon--size32 mr-2" src="/techHQ/progIcons/security/malware/adwcleaner.png" alt="ADWCleaner graphic">Malwarebyte's AdwCleaner</a></li>
</ul>