block-closing-brace-newline-before: always-multi-line
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: always
leading-zero: false
