
extends: stylelint-config-standard
syntax: scss
plugins:
  - stylelint-scss
rules:
  no-empty-source: ~
  block-no-empty: ~
  color-no-invalid-hex: true
  indentation:
    - 2
    - except:
      - value
  max-empty-lines: 1
  comment-empty-line-before: always
  selector-list-comma-newline-after: always
  color-hex-length: long
  no-descending-specificity: true
