processors:
  - stylelint-processor-html
extends: stylelint-config-standard
syntax: scss
plugins:
  - stylelint-scss
rules:
  no-empty-source: ~
  block-no-empty: ~
  color-no-invalid-hex: true
  comment-empty-line-before:
    - always
    - ignore:
      - stylelint-commands
      - after-comment
  indentation:
    - 2
    - except:
      - value
  max-empty-lines: 1
