<?php

	$the_title = ' Security Section - Removing Data and not just Deleting';
  $sitePath = "/home/xmetalx1/public_html";
  include $sitePath . "/templates/tech/baseTechSecurityTemp.tpl";
?>
    <div class="panel panel-default">
        
        <div class="panel-heading">Security Removing Data from your computer</div>
        
        <div class="panel-body"> Here is a topic I forgot about putting on the site . Recently on the news they showed how when you get rid of computer, how anyone can get your information within minutes... personal records, social security numbers, tax data and more ... .Although I do not keep that sort of thing on my machine, some do... I can not tell you exactly where all of your files are to remove (all your tax info, what files have S.S. Numbers... etc) that will very by machine and the program you use... but i will give you a few bits of information 
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">&quot;But I hit delete, so it must be gone&quot;</div>
        <div class="panel-body">
            <p class="justify">Now Seriously think... if that were true, HOW WOULD these &quot;un-delete programs&quot; works?... This may not be right, but it's a close example from what I know </p>
            <ul>
                <li>
                    <p class="justify"> Picture you want a book REMOVED from the library... you take it off the shelf and put it on the table next to the trash can ....sure its off the shelf and not where it normally would be, but it's still there.... for anyone to pick up </p>
                </li>
            </ul>
        </div>
    </div>


    <div class="panel panel-default">
        <div class="panel-heading">Can I ever really remove all the data?</div>
        <div class="panel-body">
            <p> <img src="../smiles/mad/argue.gif" alt="Yes and No Argueing Smiles" width="60" height="24" /> </p>
            <p class="justify">Despite what some members of my family have told me (I am the &quot;computer guy&quot; in the family), yes... sure its a matter of how BAD the person wants to get the data, but for the most part you can protect yourself ... you don't need these advertised &quot;$40.00 disk wiping programs&quot;... a disk wiping program IS WHAT you need though. Eraser (click the Blue link below) is one of the best I have tested out of ALOT of programs, and it is completely FREE. </p>
            <p class="mainSiteUpdates">(how do i know?.... i do have a few programs ( <a href="http://www.briggsoft.com/" target="_blank">directory snoop</a>, search and <a href="http://www.iolo.com" target="_blank"> recovery's advanced recover tool (in system mechanic's suite)</a>....that can read the contents of the raw drive..... some more advanced programs then these are available for people who really know what they are doing. </p>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Panel heading without title</div>
        <div class="panel-body">
            <p class="justify">Eraser will remove data left in Free Space, remove Files and Directories to... I have seen alot of tools with file wipers in them, but this is the best one, if you ask me... this is Open Source (anyone can download the source code and make modifications), or you can download the program by itself... for those who don't know, YES ITS FREE (no ad ware/spyware or other junk) </p>
            <p class="justify">What this program does is it overwrites the file (freespace, directory ... whatever you tell it to) with data ... 1 pass of just &quot;00000000&quot;, 3 - 7 passes of random patterns, or the high 35 wipe pass ... each of these come default, but if you choose, each wipe (like the 35 pass ... can be configured line by line so the first pass is random data generated by your pc's clock ... the next &quot;dasdhertyetetete' (you pressing a ton of random keys on your keyboard), next random again, the next &quot;Get off my system you stupid file&quot; or whatever.... if you don't want that, Eraser comes with presets, so don't think &quot;This sounds good, but I don't have time or the knowledge to configure all that&quot; <img src="../smiles/yahoo_Smiles/crazy.gif" alt="Going Crazy smile" width="35" height="26" /> </p>
            <p class="header"> <a href="http://www.heidi.ie/eraser/" target="_blank">Eraser</a> - MY Favorite Drive Wiping Tool </p>
        </div>
    </div>
    <?php include $sitePath . "/modules/tech/baseTechFooter.tpl"; ?>